


###
POST localhost:8080/sessions
Content-Type: application/json

{
  "email" : "passwordmanager@hotmail.fr",
  "password": "passwordmanager"
}

###
POST localhost:8080/sessions
Content-Type: application/json

{
  "email" : "password2@hotmail.fr",
  "password": "password2"
}

###
POST localhost:8080/employe
Content-Type: application/json

{
    "firstName" : "u11",
    "lastName" : "pass11",
    "password" : "passwordmanager",
    "soldeConge" : 10,
    "soldeRtt" : 10,
    "email" : "passwordmanager@hotmail.fr",
    "roles" : ["MANAGER"],
    "departementId" : 1,
    "managerId": 1

}


###
POST localhost:8080/departement
Content-Type: application/json

{
  "name" : "departementTest"
}

###
PUT localhost:8080/absence/statut/9
Content-Type: application/json

{
  "dateDebut" : "2023-08-10",
  "dateFin" : "2023-08-13",
  "statut" : "REJETEE",
  "typeAbsence" : "RTT",
  "motif": "",
  "employeId" : 2
}

###
PUT localhost:8080/jouroff
Content-Type: application/json

{
  "id" : 1,
  "jour" : "2023-08-24",
  "typeJour": "RTT_EMPLOYEUR",
  "description" : "vac"
}

###

###

###

PUT localhost:8080/employe/newpassword/1
Content-Type: application/json

{
"firstName" : "te",
"lastName" : "teteet",
"soldeConge" : 1,
"soldeRtt" : 1,
"email" : "passwordm@hotmail.fr",
"roles" : ["MANAGER"],
"departementId" : 1,
"managerId": 5,
  "password": "6666666666666666"
}


###

POST localhost:8080/logout
Content-Type: application/json

###
GET localhost:8080/jouroff


###
POST localhost:8080/email
Content-Type: application/json

{
  "email": "antoine.ligerot@outlook.fr",
  "content": "test bonjour"
}

###
GET https://calendrier.api.gouv.fr/jours-feries/metropole/2023.json
###

POST localhost:8080/jouroff/jourferie

###
DELETE localhost:8080/employe/delete/3
###
POST localhost:8080/absence
Content-Type: application/json

{
  "dateDebut" : "2025-06-13",
  "dateFin" : "2025-06-30",
  "statut" : 1,
  "typeAbsence" : "RTT",
  "motif": "tetestests",
  "employeId" : 6
}


###
DELETE localhost:8080/absence/5
Content-Type: application/json


